api_version = "2026-07"
uid = "8cab04a6-86d4-6b49-a627-645cb34b41c8c6f4e957"

[[extensions]]
name = "t:name"
handle = "look-bundle-discount"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
