# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c041910b1bc5ce1c8e9a465ac940ec05"
name = "Thank You Continue"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
